name: appauth
description: A Flutter Firebase Authentication app
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core + auth
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  math_expressions: ^2.5.1



  # Google sign-in
  google_sign_in: ^6.2.1

  # Optional UI helpers
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
